### ISSUE TITLE
Title Bar moves offscreen and unable to Drag & reset position

### ISSUE THREAD

**Issue by DNGR369** [PapirusDevelopmentTeam/materia-vlc#1]
Hi, I'm having an issue where the player is stuck (and opens) below the level of my taskbar and I'm unable to Drag the player anywhere on the screen. I am able to Maximize, but not Drag the player anywhere while it's a small window. The taskbar for the skin is on the bottom, and that's clearly out of reach in my case.

I've tried Shift + Right-Click on the Taskbar icon and select 'Move', but the cursor has nothing to grab onto for some reason and cancels-out. Not sure what to do here, besides delete the skin and re-install, but that may not help in the future.

If there's a quick fix, please let me know!

Thanks.

![F4MlSb97cY](https://user-images.githubusercontent.com/78584062/157185865-f654c5b5-8039-4fd0-9ec3-77359da169f3.png)

**Comment by lyh16** [comment]
Can confirm the same issue occurs on Ubuntu 20.04.
Dragging the VLC window around is impossible, and once maximized, the control bar is out of reach.

![image](https://user-images.githubusercontent.com/41638369/158142590-4970e166-fe41-4ba1-a3ee-bcc2a82130fd.png)

**Comment by abhirajshourya** [comment]
Perhaps you could change the max-height and max-width to something reasonable like 720 & 360 in theme.xml @ line-171 respectively so that it won't max out of the screen.

PS. I really love the skin, please tweak these and see if that works or make the main player window movable/draggable.

**Comment by varlesh** [comment]
`Video` widget not support action "move"

**Comment by varlesh** [comment]
I'm add "move" action for background and reduce skin by vertical size. BUT move not worked when you play video file (becuase not support this). It's only worked when you start empty vlc or play audio files
